-- ----------------------------
-- Table structure for CODE_TEST
-- ----------------------------
DROP TABLE "CODE_TEST";
CREATE TABLE "CODE_TEST" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "VALUE" NVARCHAR2(100) VISIBLE ,
  "LABEL" NVARCHAR2(100) VISIBLE ,
  "TYPE" NVARCHAR2(100) VISIBLE ,
  "DESCRIPTION" NVARCHAR2(100) VISIBLE ,
  "SORT" NUMBER(11) VISIBLE ,
  "STATUS" NCHAR(1) VISIBLE DEFAULT 0 ,
  "TEST_VALUE" NVARCHAR2(100) VISIBLE 
);
ALTER TABLE "CODE_TEST" ADD  PRIMARY KEY ("ID");
-- ----------------------------
-- Table structure for SYS_DICT
-- ----------------------------
DROP TABLE "SYS_DICT";
CREATE TABLE "SYS_DICT" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "VALUE" NVARCHAR2(100) VISIBLE ,
  "LABEL" NVARCHAR2(100) VISIBLE ,
  "TYPE" NVARCHAR2(100) VISIBLE ,
  "DESCRIPTION" NVARCHAR2(100) VISIBLE ,
  "SORT" NUMBER(11) VISIBLE ,
  "STATUS" NCHAR(1) VISIBLE DEFAULT 0  
 
);
ALTER TABLE "SYS_DICT" ADD  PRIMARY KEY ("ID");
COMMENT ON COLUMN "SYS_DICT"."ID" IS '111';
COMMENT ON COLUMN "SYS_DICT"."VALUE" IS '222';
COMMENT ON COLUMN "SYS_DICT"."LABEL" IS '222';
COMMENT ON COLUMN "SYS_DICT"."TYPE" IS '222';
COMMENT ON COLUMN "SYS_DICT"."DESCRIPTION" IS '222';
COMMENT ON COLUMN "SYS_DICT"."SORT" IS '222';
COMMENT ON COLUMN "SYS_DICT"."STATUS" IS '222';

-- ----------------------------
-- Records of "SYS_DICT"
-- ----------------------------
INSERT INTO "SYS_DICT" VALUES (NULL, 'vvvvvvsss', 'vvvv', 'vvvv', 'vvvvv', '0', '0');
INSERT INTO "SYS_DICT" VALUES (NULL, 'java', '1', 'lang', '1', '0', '0');
INSERT INTO "SYS_DICT" VALUES (NULL, 'python', 'python编程语言', 'lang', '系统语言', '0', '0');
INSERT INTO "SYS_DICT" VALUES (NULL, 'php', 'php', 'lang', '系统语言', '5', '0');

-- ----------------------------
-- Table structure for SYS_MENU
-- ----------------------------
DROP TABLE "SYS_MENU";
CREATE TABLE "SYS_MENU" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "PID" NUMBER(11) VISIBLE NOT NULL ,
  "TITLE" NVARCHAR2(100) VISIBLE ,
  "ICON" NVARCHAR2(100) VISIBLE ,
  "HREF" NVARCHAR2(100) VISIBLE ,
  "SPREAD" NVARCHAR2(100) VISIBLE ,
  "SORT" NUMBER(11) VISIBLE ,
  "IS_TOP" NVARCHAR2(1) VISIBLE ,
  "DEL_FLAG" NVARCHAR2(1) VISIBLE ,
  "LEVELS" NUMBER(11) VISIBLE ,
  "TYPE" NVARCHAR2(12) VISIBLE ,
  "PERMISSION" NVARCHAR2(200) VISIBLE 
);
ALTER TABLE "SYS_MENU" ADD  PRIMARY KEY ("ID");

-- ----------------------------
-- Records of "SYS_MENU"
-- ----------------------------
INSERT INTO "SYS_MENU" VALUES (NULL, 0, 'Cool后台管理系统', '&#xe75c;', NULL, '1', '1', '0', '0', '0', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 1, '系统管理', 'fa-desktop', NULL, '0', '1', '1', '0', '1', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 1, '内容管理', 'fa-file-word-o', NULL, '0', '2', '1', '0', '1', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 1, '生产管理', 'fa-desktop', NULL, '0', '3', '1', '0', '1', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 18, 'codeTest', 'fa-commenting-o', '/codeTest/list.do', '0', '1', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 7, '年度生产计划', 'fa-file-o', NULL, NULL, '0', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 4, '生产计划管理', 'fa-file-o', NULL, NULL, '0', '0', '0', '2', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 7, '月度生产计划', 'fa-file-o', NULL, NULL, '0', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 2, '我的面板', 'fa-television', NULL, '0', '2', '0', '0', '2', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 9, '个人信息', 'fa-vcard-o', '/user/personInfo.do', '0', '1', '0', '0', '3', '0', 'user:personInfo');
INSERT INTO "SYS_MENU" VALUES (NULL, 9, '修改密码', 'fa-gear', '/user/pwd.do', '0', '2', '0', '0', '3', '0', 'user:pwd');
INSERT INTO "SYS_MENU" VALUES (NULL, 2, '系统设置', 'fa-cogs', NULL, '0', '3', '0', '0', '2', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 12, '用户管理', 'fa-user-o', '/user/list.do', '0', '1', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 12, '角色管理', 'fa-user-circle', '/role/list.do', '0', '2', '0', '0', '3', '0', 'role:list');
INSERT INTO "SYS_MENU" VALUES (NULL, 12, '菜单管理', 'fa-window-restore', '/menu/list.do', '0', '3', '0', '0', '3', '0', 'menu:list');
INSERT INTO "SYS_MENU" VALUES (NULL, 3, '网站管理', 'fa-window-maximize', NULL, '0', '1', '0', '0', '2', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 16, '友链管理', 'fa-link', '/friendLink/list.do', '0', '7', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 2, '系统监控', 'fa-eye', NULL, '0', '3', '0', '0', '2', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 18, '连接池监视', 'fa-chain-broken', '/druid/index.html', '0', '2', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 12, '文件管理', 'fa-file-word-o', '/res/ckfinder/_samples/standalone_v1.html', '0', '5', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 16, '会员管理', 'fa-users', '/user/list.do', '0', '2', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 12, '字典管理', 'fa-file-o', '/dict/list.do', '0', '6', '0', '0', '3', '0', 'dict:list');
INSERT INTO "SYS_MENU" VALUES (NULL, 2, '系统工具', 'fa-steam-square', NULL, '0', '4', '0', '0', '2', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 23, '代码生成', 'fa-cc', '/codeGenerator/form.do', '0', '0', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 23, '生成测试', 'fa-hand-peace-o', '/test/list.do', '0', '2', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 23, '定时任务', 'fa-hourglass-2', '/quartz/list.do', '0', '3', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 23, 'Cron生成器', 'fa-file-excel-o', '/res/cron/index.htm', '0', '4', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 17, '新增', NULL, NULL, '0', '0', '0', '0', '4', '1', 'flink:add');
INSERT INTO "SYS_MENU" VALUES (NULL, 17, '删除', NULL, NULL, '0', '5', '0', '0', '4', '1', 'flink:delete');
INSERT INTO "SYS_MENU" VALUES (NULL, 17, '修改', NULL, NULL, '0', '0', '0', '0', '4', '1', 'flink:update');
INSERT INTO "SYS_MENU" VALUES (NULL, 12, '机构管理', 'fa-university', '/org/list.do', '0', '4', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 13, '增加用户', NULL, NULL, '0', '1', '0', '0', '4', '0', 'user:add');
INSERT INTO "SYS_MENU" VALUES (NULL, 13, '查看用户', NULL, NULL, '0', '2', '0', '0', '4', '0', 'user:list');
INSERT INTO "SYS_MENU" VALUES (NULL, 12, 'CodeTest管理', 'fa-battery-0', '/codeTest/list.do', '0', '7', '0', '0', '3', '0', NULL);
INSERT INTO "SYS_MENU" VALUES (NULL, 23, '报表管理', 'fa-bar-chart-o', '/chart/list.do', '0', '4', '0', '0', '3', '0', NULL);

-- ----------------------------
-- Table structure for SYS_ORG
-- ----------------------------
DROP TABLE "SYS_ORG";
CREATE TABLE "SYS_ORG" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "PID" NUMBER(11) VISIBLE NOT NULL ,
  "NAME" NVARCHAR2(100) VISIBLE NOT NULL ,
  "SORT" NUMBER VISIBLE NOT NULL ,
  "TYPE" NCHAR(1) VISIBLE NOT NULL 
);
ALTER TABLE "SYS_ORG" ADD  PRIMARY KEY ("ID");

-- ----------------------------
-- Records of "SYS_ORG"
-- ----------------------------
INSERT INTO "SYS_ORG" VALUES (NULL, '-1', '北京诚科技有限公司', '1', '0');
INSERT INTO "SYS_ORG" VALUES (NULL, '1', '开发部', '1', '1');
INSERT INTO "SYS_ORG" VALUES (NULL, '1', '法务部', '2', '1');
INSERT INTO "SYS_ORG" VALUES (NULL, '1', '行政部', '3', '1');
INSERT INTO "SYS_ORG" VALUES (NULL, '2', '前端开发组', '1', '1');
INSERT INTO "SYS_ORG" VALUES (NULL, '2', '后台开发组', '1', '1');

-- ----------------------------
-- Table structure for SYS_QUARZ
-- ----------------------------
DROP TABLE "SYS_QUARZ";
CREATE TABLE "SYS_QUARZ" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "JOB_NAME" NVARCHAR2(50) VISIBLE ,
  "JOB_GROUP" NVARCHAR2(50) VISIBLE ,
  "CLASS_PATH" NVARCHAR2(50) VISIBLE ,
  "CRON_STR" NVARCHAR2(50) VISIBLE ,
  "STATE" NVARCHAR2(1) VISIBLE DEFAULT 1 ,
  "MARK" NVARCHAR2(100) VISIBLE 
);
ALTER TABLE "SYS_QUARZ" ADD  PRIMARY KEY ("ID");

-- ----------------------------
-- Records of "SYS_QUARZ"
-- ----------------------------
INSERT INTO "SYS_QUARZ" VALUES (NULL, '测试定时器', '第一组', 'com.quartz.TestQuartz', '0/5 * * * * ?', '1', '每隔5分运行一次');
INSERT INTO "SYS_QUARZ" VALUES (NULL, '测试定时器2', '第一组', 'com.quartz.Test2Quartz', '0/2 * * * * ?', '1', '每2秒打印一次');

-- ----------------------------
-- Table structure for SYS_ROLE
-- ----------------------------
DROP TABLE "SYS_ROLE";
CREATE TABLE "SYS_ROLE" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "NAME" NVARCHAR2(255) VISIBLE ,
  "USEABLE" NVARCHAR2(64) VISIBLE  DEFAULT 0 
);
ALTER TABLE "SYS_ROLE" ADD  PRIMARY KEY ("ID");
-- ----------------------------
-- Records of "SYS_ROLE"
-- ----------------------------
INSERT INTO "SYS_ROLE" VALUES (NULL, '超级管理员', '0');
INSERT INTO "SYS_ROLE" VALUES (NULL, '内容管理员', '0');
INSERT INTO "SYS_ROLE" VALUES (NULL, '系统管理员', '0');
-- ----------------------------
-- Table structure for SYS_ROLE_MENU
-- ----------------------------
DROP TABLE "SYS_ROLE_MENU";
CREATE TABLE "SYS_ROLE_MENU" (
  "ROLE_ID" NVARCHAR2(255) VISIBLE ,
  "MENU_ID" NVARCHAR2(255) VISIBLE 
);


-- ----------------------------
-- Records of "SYS_ROLE_MENU"
-- ----------------------------
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '2');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '3');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '4');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '5');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '6');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '7');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '7');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '8');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '9');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '10');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '11');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '12');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '12');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '13');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '14');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '15');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '16');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '17');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '18');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '19');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '20');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '21');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '22');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '23');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '24');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '25');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '26');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '27');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '28');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '29');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '30');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '31');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '32');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '33');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1', '34');
INSERT INTO "SYS_ROLE_MENU" VALUES ('1','35');
INSERT INTO "SYS_ROLE_MENU" VALUES ('2', '29');
INSERT INTO "SYS_ROLE_MENU" VALUES ('2', '30');
INSERT INTO "SYS_ROLE_MENU" VALUES ('2', '28');
INSERT INTO "SYS_ROLE_MENU" VALUES ('2', '17');
INSERT INTO "SYS_ROLE_MENU" VALUES ('2', '21');
INSERT INTO "SYS_ROLE_MENU" VALUES ('2', '16');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '2');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '9');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '10');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '11');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '12');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '13');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '32');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '33');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '14');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '15');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '31');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '20');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '22');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '34');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '18');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '5');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '19');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '23');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '24');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '25');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '26');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '27');
INSERT INTO "SYS_ROLE_MENU" VALUES ('3', '35');


-- ----------------------------
-- Table structure for SYS_USER
-- ----------------------------
DROP TABLE "SYS_USER";
CREATE TABLE "SYS_USER" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "LOGIN_NAME" NVARCHAR2(255) VISIBLE ,
  "PWD" NVARCHAR2(255) VISIBLE ,
  "IMG" NVARCHAR2(255) VISIBLE ,
  "EMAIL" NVARCHAR2(255) VISIBLE ,
  "SEX" NVARCHAR2(2) VISIBLE ,
  "MOBILE" NVARCHAR2(255) VISIBLE ,
  "STATUS" NCHAR(1) VISIBLE DEFAULT 0 ,
  "NAME" NVARCHAR2(255) VISIBLE ,
  "ROLE_ID" NUMBER(11) VISIBLE ,
  "ORG_ID" NUMBER(11) VISIBLE 
);
ALTER TABLE "SYS_USER" ADD  PRIMARY KEY ("ID");

-- ----------------------------
-- Records of "SYS_USER"
-- ----------------------------
INSERT INTO "SYS_USER" VALUES (NULL, 'admin', '21232f297a57a5a743894a0e4a801fc3', '/upload/zhuyubing.jpg', 'xxoo@gmail.com', NULL, '15022222222', '0', 'xxoo', '1', '2');
INSERT INTO "SYS_USER" VALUES (NULL, 'tom', '21232f297a57a5a743894a0e4a801fc3', '/upload/zhuyubing.jpg', '111@qq.com', NULL, '15022222222', '0', 'aa', '2', '2');
INSERT INTO "SYS_USER" VALUES (NULL, 'cc', 'e10adc3949ba59abbe56e057f20f883e', '/upload/images/20191009/2019100909390730822060.JPG', '11a1@qq.com', NULL, '13545698712', '0', 'sfnv', '2', '3');
INSERT INTO "SYS_USER" VALUES (NULL, 'nn', '827ccb0eea8a706c4c34a16891f84e7b', '/upload/images/20190923/2019092313394437272291.JPG', '1a11@qq.com', NULL, '13745698712', '0', 'realnfame', '2', '3');
INSERT INTO "SYS_USER" VALUES (NULL, '33', 'e10adc3949ba59abbe56e057f20f883e', '/upload/images/20190926/2019092610143915029153.JPG', '111@qq.com', NULL, '13845698712', '0', 'dd', '2', '2');



-- ----------------------------
-- Table structure for WEB_FLINK
-- ----------------------------
DROP TABLE "WEB_FLINK";
CREATE TABLE "WEB_FLINK" (
  "ID" NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY ,
  "WEBNAME" NVARCHAR2(255) VISIBLE ,
  "ALINK" NVARCHAR2(255) VISIBLE ,
  "EMAIL" NVARCHAR2(255) VISIBLE ,
  "ADDTIME" DATE VISIBLE ,
  "DISPOS" NVARCHAR2(255) VISIBLE ,
  "CONTENT" NCLOB VISIBLE 
);
ALTER TABLE "WEB_FLINK" ADD  PRIMARY KEY ("ID");

-- ----------------------------
-- Records of "WEB_FLINK"
-- ----------------------------
INSERT INTO "WEB_FLINK" VALUES (NULL, '新浪', 'http://www.sina.com.cn', '40930845@qq.com', TO_DATE('2019-08-27 15:15:40', 'SYYYY-MM-DD HH24:MI:SS'), '首页', '很好');


